# Generated by Django 5.1.15 on 2026-05-18 22:05

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import portal.backend


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "submission_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("original_prompt", models.TextField()),
                ("resolved_dataset", models.TextField(blank=True)),
                (
                    "backend_profile",
                    models.CharField(
                        choices=[
                            (
                                portal.backend.BackendProfile["SERVICEX_AWKWARD"],
                                "ServiceX + Awkward",
                            ),
                            (portal.backend.BackendProfile["RDF"], "RDF"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("queue_position", models.PositiveIntegerField(blank=True, null=True)),
                ("queue_depth_at_submission", models.PositiveIntegerField(default=0)),
                (
                    "submitted_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("runtime", models.DurationField(blank=True, null=True)),
                ("failure_message", models.TextField(blank=True)),
                ("generated_code", models.TextField(blank=True)),
                ("result_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="JobArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("artifact_kind", models.CharField(max_length=64)),
                ("path", models.TextField()),
                ("is_canonical", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="portal.job",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
    ]
